#!/bin/sh

if [ -d /usr/lib/ccache ]; then
    export PATH="/usr/lib/ccache:$PATH"
fi
debian/rules clean 2>&1
dpkg-source --before-build .
debian/rules build 2>&1
xvfb-run -a --server-args="-screen 0 1024x768x24+32" \
    dbus-run-session -- debian/tests/testsuite.xsession
